---
apiVersion: tekton.dev/v1alpha1
kind: PipelineResource
metadata:
  name: github-tekton-examples
  namespace: default
spec:
  type: git
  params:
    - name: url
      value: https://github.com/prodanlabs/tekton-examples
    - name: revision
      value: main